---
title: "Aula 01"
output: html_notebook
---

## Módulo 1 - Vetores Aleatórios


### 1.1 - Variável Aleatória


### 1.2 - Vetor Aleatórios

### 1.3 -

### 1.4 - Variância e Desvio Padrão
- fornece informação sobre a dispersão dos valores da variável em relação à respectiva média

### 1.5 - Covariâncias
- grau de relacionamento linear entre duas variáveis
- quanto menor em módulo (mais próximo a zero) = as variáveis estão menos associadas -> variáveis independentes
- negativa: variam em sentidos opostos
- matriz simétrica
#### 1.5.1 - Variância Total
- soma dos elementos da diagonal principal da matriz de Covariâncias
#### 1.5.2 - Variância Generalizada
- raiz quadrada do determinante da matriz de covariâncias

### 1.6 - Correlação
- relacionamento linear entre duas variáveis
- valor em módulo, quanto mais próximo de 1, maior a associação entre as variáveis
- varia de -1 a 1
- linear de Pearson
- diagonal da matriz = 1

### 1.7 - Teorema da decomposição espectral

```{r}

```


## Módulo 2 - Estimação de Parâmetros em Distribuições Multivariadas


## Módulo 3 - Análise de Componentes Principais